version: '3.8'
services:
    gobackend:
        container_name: mygobackend
        restart: always
        build: .
        ports:
            - '80:8080'
        
    db: 
        container_name: mysql
        image: mysql:8.0
        restart: always
        ports:
         - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: password
     
         
